name: sqd
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pyscf
  - pip
  - pip:
      - ffsim
      - qiskit
      - qiskit-aer
      - qiskit-addon-sqd
      - matplotlib
      - pandas
      - scipy
      - pytest
